pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/Pruthvichinna/devops-cloud-pipeline.git'
            }
        }
        stage('Build') {
            steps {
                sh 'docker build -t flask-app .'
            }
        }
        stage('Test') {
            steps {
                sh 'docker run flask-app python3 -m unittest discover || echo "No tests found."'
            }
        }
        stage('Push to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-pass', variable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u your-dockerhub-username --password-stdin'
                    sh 'docker tag flask-app your-dockerhub-username/flask-app:latest'
                    sh 'docker push your-dockerhub-username/flask-app:latest'
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/'
            }
        }
    }
}